# need a copy of docker running
sudo: required
services:
  - docker
# build our image using dockerfile.dev
before_install:
  - docker build -t bman1592/docker-react -f Dockerfile.dev .
# tell travis how to run our test suite
scripts:
  - docker run -e CI=true bman1592/docker-react npm run test

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: “elasticbeanstalk-us-west-2-243738880510”
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY